GET http://localhost:3001/api/blogs/


###
GET http://localhost:3001/api/users/


###
GET http://localhost:3001/api/wrong/

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2F1a29yYSIsImlkIjoiNjBlM2VlYmYwN2YyNzQzMjU3YWM5MGYxIiwiaWF0IjoxNjI1NTY1OTczfQ.2qpe8USWciwA9rZXvg6CFYwW-jcqRf0m26rusmU5FNQ

{
  "title": "test with good token",
  "author": "mk",
  "url": "foo",
  "likes": 123332
}


### invalid token
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer IIeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2F1a29yYSIsImlkIjoiNjBlM2VlYmYwN2YyNzQzMjU3YWM5MGYxIiwiaWF0IjoxNjI1NTY1OTczfQ.2qpe8USWciwA9rZXvg6CFYwW-jcqRf0m26rusmU5FNQ

{
  "title": "test",
  "author": "mk",
  "url": "foo",
  "likes": 123332
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "another test more 2",
  "author": "mk",
  "url": "bar",
  "likes": 0
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "test",
  "author": "mk",
  "likes": 123332
}

###
DELETE http://localhost:3001/api/blogs/60e2cb8c215793199820fd94 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2F1a29yYSIsImlkIjoiNjBlM2VlYmYwN2YyNzQzMjU3YWM5MGYxIiwiaWF0IjoxNjI1NTY1OTczfQ.2qpe8USWciwA9rZXvg6CFYwW-jcqRf0m26rusmU5FNQ


###
PUT http://localhost:3001/api/blogs/60ded9c89d1326559fbfc6f1 HTTP/1.1
content-type: application/json

{
  "author": "Fofoo",
  "likes": 123
}

