GET http://localhost:3001/api/blogs/

###
GET http://localhost:3001/api/wrong/

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "test",
  "author": "mk",
  "url": "foo",
  "likes": 123332
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "another test more 2",
  "author": "mk",
  "url": "bar",
  "likes": 0
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "test",
  "author": "mk",
  "likes": 123332
}

###
DELETE http://localhost:3001/api/blogs/60e2cb8c215793199820fd94


###
PUT http://localhost:3001/api/blogs/60ded9c89d1326559fbfc6f1 HTTP/1.1
content-type: application/json

{
  "author": "Fofoo",
  "likes": 123
}

