GET http://localhost:3001/api/blogs/

###
GET http://localhost:3001/api/wrong/

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "test",
  "author": "mk",
  "url": "foo",
  "likes": 123332
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "another test more 2",
  "author": "mk",
  "url": "bar",
  "likes": 0
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "test",
  "author": "mk",
  "likes": 123332
}
